
spring.datasource.url=jdbc:postgresql://ep-winter-credit-ate2h0mo-pooler.c-9.us-east-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=neondb_owner
spring.datasource.password=npg_Jk4dQWNcH3PX

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8081

logging.file.name=logs/roommate-ai.log
logging.level.root=INFO
logging.level.com.example.roommateai=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n